dotconf_assist_admin_email_address: "name@example.com"
dotconf_assist_inform_email_address: "name@example.com"
splunk_admin_user_name: ""
splunk_admin_password: ""
dotconf_assist_admin_user_name: ""
dotconf_assist_admin_password: ""
dotconf_assist_domain: "localhost:3000"
search_head_cluster_vip: "viphostname.com"
search_head_cluster: "hostname1.com,hostname2.com,hostname3.com"
proxy_host: ""
proxy_port: ""
about_link: ""
faq_link: "http://example.com/"
reference_link: "http://example.com/"
unixapp_link: "http://example.com/"
unixapp_dashboard_link: "http://example.com/"
appteam_link: "http://example.com/"
serviceid_link: "http://example.com/"
start_guide_link: "http://example.com/"
input_link: "http://example.com/"
create_account_link: "http://example.com/"
deploy_app_link: "http://example.com/"
enable_size_cost_estimation_page: false