development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: changeme
  password: changeme
  host: 127.0.0.1
  database: splunkassist

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: changeme
  password: changeme
  host: 127.0.0.1
  database: splunkassist_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: changeme
  password: changeme
  host: example.com
  database: splunkassist